# Generated by Django 3.0.6 on 2020-05-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('innerinput', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TextOutpout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theoutput', models.TextField()),
            ],
        ),
    ]
